[package]
name = "protunel"
version = "0.3.1"
description = "Lightweight Windows desktop app for managing SSH SOCKS5 tunnels and local proxies without external SSH tools."
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "protunel_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.40.1", features = ["bundled"] }
keyring = "4.1.5"
uuid = { version = "1.24.0", features = ["v4", "serde"] }
tokio = { version = "1.53.1", features = ["full"] }
tokio-util = "0.7.19"
thiserror = "2.0.19"
russh = { version = "0.62.4", default-features = false, features = ["ring", "flate2", "rsa"] }
fast-socks5 = "1.0.0"
log = "0.4.33"
anyhow = "1.0.104"
tauri-plugin-single-instance = "2.4.3"
tauri-plugin-updater = "2.10.1"
tauri-plugin-process = "2.3.1"
tauri-plugin-notification = "2.3.3"
tauri-plugin-autostart = "2.5.1"
tauri-plugin-clipboard-manager = "2.3.2"

